version: '3.8'

services:

  gateway:
    build: ./gateway  #build the Dockerfile inside the gateway folder
    ports:
    - "80:80"
    depends_on:
    - redis
    networks:
    - synaptic-network
  
  redis:
    image: "redis:latest"
    ports:
    - "6379:6379"
    networks:
    - synaptic-network
  
  worker:
    build: ./working-nodes  #build the Dockerfile inside the working-nodes folder
    environment:
      - REDIS_HOST=redis     # Tell Python where to find the database
      - OLLAMA_HOST=ollama   # Tell Python where to find the AI model
    depends_on:
      - redis
      - ollama  
    networks:
      - synaptic-network
    
  ollama:
    image: "ollama/ollama:latest"
    volumes: 
      - ./ollama_data:/root/.ollama # Save models here so they don't delete on restart
    networks:
      - synaptic-network


networks:
  synaptic-network:
    driver: bridge     # Creates a private virtual Wi-Fi for containers