version: '3.8'

services:

  gateway:
    build: ./gateway  #build the Dockerfile inside the gateway folder
    container_name: synapse-gateway
    cap_add:
      - NET_ADMIN
    profiles: ["control"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
    - ./gateway/logs:/var/log/nginx  # Save logs here so i can use it in debugging
    - ./gateway/lua:/usr/local/openresty/lua/ # Copy the Lua scripts to the container
    ports:
    - "80:80"
    depends_on:
    - redis
    networks:
    - synaptic-network
  
  redis:
    image: "redis:latest"
    profiles: ["control"]
    ports:
    - "6379:6379"
    networks:
    - synaptic-network
  
  admin-dashboard:
    build: ./admin
    profiles: ["control"]
    ports:
      - "8501:8501"
    depends_on:
      - redis
      - gateway
    networks:
      - synaptic-network


  worker-1:
      pid: "host"
      build:
        context: ./working-nodes
        args:
          - HF_TOKEN=${HF_TOKEN}
      profiles: ["compute"]
      environment:
        - PINECONE_API_KEY=${PC_TOKEN}
        - SERVICE_NAME=worker-1
        - PYTHONUNBUFFERED=1
      ports: 
        - "5000:5000"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu, utility]
      networks:
        - synaptic-network

  worker-2:
      pid: "host"
      build: 
        context: ./working-nodes
        args:
          - HF_TOKEN=${HF_TOKEN}
      profiles: ["compute"]
      environment:
        - PINECONE_API_KEY=${PC_TOKEN} 
        - SERVICE_NAME=worker-2
        - PYTHONUNBUFFERED=1
      ports: 
        - "5001:5000"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu, utility]
      networks:
        - synaptic-network

  worker-3:
      pid: "host"
      build: 
        context: ./working-nodes
        args:
          - HF_TOKEN=${HF_TOKEN}
      profiles: ["compute"]
      environment:
        - PINECONE_API_KEY=${PC_TOKEN} 
        - SERVICE_NAME=worker-3
        - PYTHONUNBUFFERED=1
      ports: 
        - "5002:5000"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu, utility]
      networks:
        - synaptic-network

  watchdog:
    build: ./watchdog  #build the Dockerfile inside the gateway/watchdog folder
    profiles: ["control"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_HOST=redis     # Tell Python where to find the database
    depends_on:
      - redis
    networks:
      - synaptic-network


networks:
  synaptic-network:
    driver: bridge     # Creates a private virtual Wi-Fi for containersiners
