#download a lightweght openresty 
FROM openresty/openresty:alpine 

#use the custom nginx.conf file to replace the default one by openresty
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

