error_log /var/log/nginx/error.log debug;  #route te errors into the error log folder for debugging purposes

events {
    worker_connections 1024;
}

http {

    resolver 127.0.0.11 ipv6=off;
    # add 1MB of shared memory for the lua script to store the state of the worker nodes
    lua_shared_dict router_state 1m; 
    #tell NGINX where to find the Redis library and the lua script 
    lua_package_path "/usr/local/openresty/lualib/?.lua;/usr/local/openresty/lua/?.lua;;";


    server {
        listen 80;
        location /api/ {          #route to http://localhost:80/api/...

            set $assigned_worker ""; #global variable to store the assigned worker node

            access_by_lua_file /usr/local/openresty/lua/router.lua;  #call the lua script to determine the worker node

            proxy_pass http://$assigned_worker;    #route to the chosen worker node
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        }
    }
}
